[tls]
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/certs/fullchain.pem"
        keyFile  = "/certs/privkey.pem"

[tls.certificates]
  [[tls.certificates]]
    certFile = "/certs/fullchain.pem"
    keyFile  = "/certs/privkey.pem"
